server:
  port: 9099
spring:
  rabbitmq:
    host: 39.108.107.103
    port: 8083
    username: guest
    password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://wugf:123456@localhost:8761/eureka

#hystrix 查看监控端点 hystrix.stream支持的最大并发
hystrix:
  config:
    stream:
      maxConcurrentConnections: 10
management:
  security:
    enabled: false
