server:
  port: 9088
spring:
  rabbitmq:
    host: 39.108.107.103
    port: 8083
    username: guest
    password: guest
  #微服务跟踪平台
  zipkin:
    base-url: http://localhost:9010
  #数据采集 1为100%
  sleuth:
    sampler:
      percentage: 1.0
key: '{cipher}4891f1ba4d936c6fd905699dd5867f30c263f65bfe179b4be5d4820ff8d3b6c8'
eureka:
  client:
    serviceUrl:
      defaultZone: http://wugf:123456@localhost:8761/eureka
#hystrix 查看监控端点 hystrix.stream支持的最大并发
hystrix:
  config:
    stream:
      maxConcurrentConnections: 10
#设置为false才能使用spring cloud端点
management:
  security:
    enabled: false
