server:
  port: 9087
spring:
  rabbitmq:
    host: 39.108.107.103
    port: 8081
    username: guest
    password: guest
key: '{cipher}f7bcd9e2e00479908792aa5e6d7c5590d5d89cf6f588fec06606c63aa67508a5'
eureka:
  client:
    serviceUrl:
      defaultZone: http://wugf:123456@localhost:8761/eureka
#hystrix 查看监控端点 hystrix.stream支持的最大并发
hystrix:
  config:
    stream:
      maxConcurrentConnections: 10
management:
  security:
    enabled: false
