server:
  port: 9088

key: '{cipher}21f7cb08fab4ae2993db498a43ea5ac219ab789795975f48e4fd05bee28dd262'
eureka:
  client:
    serviceUrl:
      defaultZone: http://wugf:123456@localhost:8761/eureka
#hystrix 查看监控端点 hystrix.stream支持的最大并发
hystrix:
  config:
    stream:
      maxConcurrentConnections: 10
management:
  security:
    enabled: false
spring:
  rabbitmq:
    host: 39.108.107.103
    port: 8081
    username: guest
    password: guest
